### ISSUE TITLE
Missing Plasmid

### ISSUE THREAD

**Issue by mweberr** [CCB-SB/plsdb#12]
Hi,
I was wondering why plasmid CP015070 is not part of the database ?
Do you use any quality filtering step ?

Best,
Michael

**Comment by SmalJonni** [comment]
Hello,
Querying CP015070 using the "Search" -> "Plasmid (by ID)" interface forwarded me to plasmid NZ_CP015070.1 in the current version of PLSDB (2020_11_19).  Then, on [this page](https://ccb-microbe.cs.uni-saarland.de/plsdb/plasmids/plasmid/NZ_CP015070.1/) I see that CP015070 is excluded from the collection due to an identical sequence. Accordingly, the sequence is present in the database by the inclusion of NZ_CP015070.1.

**Comment by mweberr** [comment]
Hi, Thank you for the response. I found the additional search option, which immediately returns the ID. However, apparently the interactive data table, with the search field on top does not allow for substring searches, which means NZ_CP015070.1, returns the row but CP015070.1 returns no result. Maybe this can be fixed.

**Comment by VGalata** [comment]
Hi @MichWeb75,

There are additional search options in the interactive table if you click on the search button (the one with the magnifying glass icon) next to the search text field. If you use that, you can select for the field/column "Plasmid" the search option "contains" and search for "CP015070.1". This will then show you the plasmid "NZ_CP015070.1" in the table.

@SmalJonni: Maybe we could add an extra note above the table to highlight that option for the other users.

Best,
Valentina

**Comment by SmalJonni** [comment]
The help text has been updated.
I will close the issue for now. 
Feel free to reopen in case clarity has not improved or further users struggle with using the table.
