### ISSUE TITLE
Error during sequence searching

### ISSUE THREAD

**Issue by phamquynhhoa** [CCB-SB/plsdb#27]
[Error report_PLSDB.pdf](https://github.com/CCB-SB/plsdb/files/14162832/Error.report_PLSDB.pdf)
I tried to search for a protein sequence in PLSDB 2023_11_03_v2. I upload a FASTA file and choose the tblastn. However, the serve keeps detecting errors automatically (picture attached).

**Comment by G-Molano-LA** [comment]
Hi @phamquynhhoa,

The report that you provided is surprising because the tblastn search implemented in PLSDB only allow the parameter "Minimal query coverage per HSP". By the way, I tested the tblastn search and it works with the example. Did you still get the same error? If so, maybe you can provide the fasta file that you use.

Bests,

Alejandra
